In [1]:
### Assignment 1: Working with NumPy

import numpy as np

# 1. 1D Array with integers from 1 to 20
arr_1d = np.arange(1, 21)

# a. Calculations [cite: 62]
print(f"Sum: {np.sum(arr_1d)}")
print(f"Mean: {np.mean(arr_1d)}")
print(f"Median: {np.median(arr_1d)}")
print(f"Standard Deviation: {np.std(arr_1d)}")

# b. Indices of elements > 10 [cite: 63]
indices = np.where(arr_1d > 10)
print(f"Indices where element > 10: {indices}")

# 2. 2D Array (4x4) [cite: 64]
arr_2d = np.arange(1, 17).reshape(4, 4)
print("\n2D Array:\n", arr_2d) # [cite: 65]
print("Transpose:\n", arr_2d.T) # [cite: 66]
print("Row-wise Sum:", np.sum(arr_2d, axis=1)) # [cite: 67]
print("Column-wise Sum:", np.sum(arr_2d, axis=0)) # [cite: 67]

# 3. Random 3x3 Arrays [cite: 68]
arr1 = np.random.randint(1, 21, (3, 3))
arr2 = np.random.randint(1, 21, (3, 3))

print("\nAddition:\n", arr1 + arr2) # [cite: 69]
print("Dot Product:\n", np.dot(arr1, arr2)) # [cite: 70]

# 4. Reshape and Slice [cite: 71]
arr_reshape = np.arange(1, 13).reshape(3, 4)
sliced_arr = arr_reshape[:2, -2:]
print("\nSliced Array (First 2 rows, last 2 columns):\n", sliced_arr)

Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398
Indices where element > 10: (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)

2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Row-wise Sum: [10 26 42 58]
Column-wise Sum: [28 32 36 40]

Addition:
 [[11 21 16]
 [21 21 25]
 [30 13  6]]
Dot Product:
 [[188 136 138]
 [500 352 338]
 [164 207 195]]

Sliced Array (First 2 rows, last 2 columns):
 [[3 4]
 [7 8]]
